"""removed_hash_column_from_posts

Revision ID: 90e82717f37b
Revises: 2043f593e68a
Create Date: 2020-09-30 02:57:19.060610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90e82717f37b'
down_revision = '2043f593e68a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('password_hash', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
